server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    url: #DB link jdbc:postgresql://localhost:5432/****
    username: #DB user
    password: #DB password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true                   #not necessary
  #    show-sql: true

    open-in-view: false                     #to remove warning, prob will cause error with db in future


  mail:
    host: smtp.gmail.com
    port: 587
    username: #Email
    password: #Password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true